name: sdtq_telagailmu_yogyakarta
description: "A new Flutter project."


version: 1.0.0+9

environment:
  sdk: ^3.7.2


dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.2
  excel: ^4.0.2
  file_picker: ^10.2.0
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  geolocator: ^14.0.2
  get: ^4.7.2
  get_storage: ^2.1.1
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.3.0
  percent_indicator: ^4.2.3
  persistent_bottom_nav_bar: ^6.2.1
  supabase_flutter: ^2.9.0
  table_calendar: ^3.2.0
  timeago: ^3.6.1
  multi_select_flutter: ^4.1.3
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_colorpicker: ^1.1.0
  dotted_border: ^3.1.0
  share_plus: ^11.1.0
  http: ^1.5.0
  path_provider: ^2.1.5
  image: ^4.3.0
  flutter_localization: ^0.3.3
  flutter_svg: ^2.2.0
  change_app_package_name: ^1.5.0
  esc_pos_utils_plus: ^2.0.4
  flutter_usb_printer: ^0.1.0+1
  blue_thermal_printer: ^1.2.3
  permission_handler: ^12.0.1
  flutter_image_compress: ^2.4.0
  url_launcher: ^6.3.2
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon" # Mengaktifkan mode adaptive
  ios: true
  # Gunakan adaptive_icon_foreground untuk lapisan depan di Android
  adaptive_icon_foreground: "assets/icon/icon.png"
  # Tentukan warna latar belakang untuk Android
  adaptive_icon_background: "#FFFFFF" # Ganti dengan kode hex warna brand sekolah Anda
  # image_path digunakan untuk iOS dan sebagai fallback
  image_path: "assets/icon/icon.png"

  windows:
    generate: true # Wajib, untuk mengaktifkan pembuatan ikon Windows
    image_path: "assets/icon/icon.png" # Path ke gambar ikon (bisa sama dengan yang utama)
    icon_size: 48 # Ukuran default, tapi paket akan membuat ukuran lain yang diperlukan



flutter:
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/webp/
    - assets/lotties/
    - assets/png/
    - assets/svg/
    - .env